zen-web-side-panel-context-mute-panel = 
    .label = 静音网页栏
    .accesskey = M
zen-web-side-panel-context-unmute-panel = 
    .label = 取消静音网页栏
    .accesskey = m
zen-web-side-panel-context-disable-ua = 
    .label = 禁用移动端 UserAgent
    .accesskey = U
zen-web-side-panel-context-enable-ua = 
    .label = 启用移动端 UserAgent
    .accesskey = M
zen-web-side-panel-context-unload = 
    .label = Unload Web Panel
    .accesskey = W
zen-web-side-panel-context-delete = 
    .label = Delete Web Panel
    .accesskey = D
zen-web-side-panel-open-in-new-tab = 
    .label = 新标签页打开
    .accesskey = N
zen-web-side-panel-context-add-to-panel = 
    .label = 添加到网页栏
    .accesskey = A
zen-sidebar-introduction-title = 欢迎使用 Zen 侧栏
zen-sidebar-introduction-description =Zen 侧栏是浏览网页的一种新方式。可点击任意图标来打开网页栏。
